<a href="https://colab.research.google.com/github/loslhp/Fundamentos-de-Data-Science-com-Python---Senai/blob/master/Aula4_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Aula4 numpy


In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])

In [3]:
arr1

array([1, 2, 3])

In [4]:
arr1[0]

1

In [5]:
##Pegar a ultima posição
arr1[len(arr1)-1]

3

In [6]:
##Pegar a ultima posição
arr1[-1]

3

In [7]:
arr2 = np.array([[1,2,3],[4,5,6,],[7,8,9]])

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2[0,0]

1

In [14]:
arr3 = np.random.randn(100)
arr3

array([-1.02384652,  0.07198466,  1.31166362, -1.19518194, -1.15487175,
        0.27017521,  1.48413725, -1.45487085,  0.92202835, -0.02736363,
       -0.61206812,  0.31909792,  0.57955491,  0.8050974 , -0.76920094,
       -1.59843811, -0.83939349,  0.66982812,  0.46948492,  0.37278007,
        1.27237889, -1.19558093, -0.11574568,  0.60940011, -1.42596405,
       -0.20900684,  1.52352749,  2.0127666 ,  0.27665491,  1.244516  ,
        0.23289548, -0.45549042, -2.36838244, -1.08608888, -2.46921751,
        1.02346329,  0.08655323,  0.75088476, -1.38354441, -1.30553199,
       -0.68401991, -1.29435915,  0.24601631, -0.41520435,  0.1467382 ,
        0.0726751 ,  0.36105483,  1.32291617,  0.75457352,  0.36736393,
        0.17885148,  1.13572152,  0.97724747,  0.77128318, -0.22094686,
        0.78285406,  0.68957863,  0.20566229,  0.63743992,  0.36528381,
        1.25494639, -1.01096315, -1.36780904,  0.58445615, -0.44602887,
       -0.11368828,  0.62218491,  0.37103205, -0.91794073, -0.03

In [24]:
##[posição inicial:quantidade de item a partir da posição inicial]
arr3[0:10]

array([-1.02384652,  0.07198466,  1.31166362, -1.19518194, -1.15487175,
        0.27017521,  1.48413725, -1.45487085,  0.92202835, -0.02736363])

In [21]:
arr3[-1]

-0.7067396907736083

In [23]:
arr4 =[arr3[0],arr3[-1]]
arr4

[-1.0238465245207728, -0.7067396907736083]

In [27]:
arr3 = np.random.rand(4,4)
arr3

array([[0.88341808, 0.86091225, 0.81099437, 0.3347422 ],
       [0.15982972, 0.1666741 , 0.71300271, 0.36621853],
       [0.73723192, 0.5805197 , 0.17135929, 0.05357277],
       [0.2511231 , 0.17662121, 0.15303289, 0.35364129]])

In [29]:
arr3[1,1]

0.1666740999445624

In [30]:
import math as mt

In [31]:
np.mean(arr3)

0.4233058832314155

In [32]:
np.std(arr3)

0.2823625239860823

In [36]:
arr6 = np.random.randn(10000)
np.mean(arr6)

-0.00179695408771749

In [50]:
arr7 = np.random.randn(5,5)
arr7

array([[ 1.03929638,  0.3787928 , -0.83192243, -0.45767824, -0.09345049],
       [ 1.77364062, -0.55846241,  0.48820871,  1.14813805, -0.37312139],
       [-0.91040782,  0.13818095, -0.3714565 , -1.29293079, -1.24001333],
       [-2.40959293,  1.4861805 , -0.00331791, -0.56941025,  0.21121826],
       [-2.5588389 ,  1.21085272,  1.13428557, -1.12935022,  0.27580322]])

In [69]:
#linha e coluna
arr7[0:3,1:3]

array([[ 0.3787928 , -0.83192243],
       [-0.55846241,  0.48820871],
       [ 0.13818095, -0.3714565 ]])

In [71]:
#[indice:quantas colunas quero]
arr7[2:5,2:5]

array([[-0.3714565 , -1.29293079, -1.24001333],
       [-0.00331791, -0.56941025,  0.21121826],
       [ 1.13428557, -1.12935022,  0.27580322]])

In [77]:
arr7[2:3]

array([[-0.91040782,  0.13818095, -0.3714565 , -1.29293079, -1.24001333]])

In [78]:
arr7[:,2:3]

array([[-0.83192243],
       [ 0.48820871],
       [-0.3714565 ],
       [-0.00331791],
       [ 1.13428557]])

In [79]:
arr71 = arr7[2:3]

In [80]:
arr72 = arr7[:,2:3]

In [81]:
np.append(arr71,arr72)

array([-0.91040782,  0.13818095, -0.3714565 , -1.29293079, -1.24001333,
       -0.83192243,  0.48820871, -0.3714565 , -0.00331791,  1.13428557])

In [84]:
arr8 = np.random.randn(6,6)
arr8

array([[ 0.17595047, -0.46400418, -0.14878971,  0.05141086,  0.46815575,
        -0.37198523],
       [ 1.58786354, -1.59653459,  1.00733449, -1.20395819,  0.14331394,
         0.27000349],
       [-1.95690437,  0.86448982,  1.00807034,  0.76752396,  0.27534839,
         0.05644369],
       [-1.00611074,  0.75805155, -2.1296968 , -1.33495405,  1.90298629,
        -0.23900619],
       [-0.61637267,  1.22298605, -0.98632522,  0.27776388,  1.26263451,
        -0.8791963 ],
       [ 0.37372154,  0.07208375, -0.2599208 ,  0.25160064, -0.97166685,
        -0.88585812]])

In [85]:
arr8[0,0] = 0
arr8

array([[ 0.        , -0.46400418, -0.14878971,  0.05141086,  0.46815575,
        -0.37198523],
       [ 1.58786354, -1.59653459,  1.00733449, -1.20395819,  0.14331394,
         0.27000349],
       [-1.95690437,  0.86448982,  1.00807034,  0.76752396,  0.27534839,
         0.05644369],
       [-1.00611074,  0.75805155, -2.1296968 , -1.33495405,  1.90298629,
        -0.23900619],
       [-0.61637267,  1.22298605, -0.98632522,  0.27776388,  1.26263451,
        -0.8791963 ],
       [ 0.37372154,  0.07208375, -0.2599208 ,  0.25160064, -0.97166685,
        -0.88585812]])

In [86]:
arr8[0:2,0:2] = 0
arr8

array([[ 0.        ,  0.        , -0.14878971,  0.05141086,  0.46815575,
        -0.37198523],
       [ 0.        ,  0.        ,  1.00733449, -1.20395819,  0.14331394,
         0.27000349],
       [-1.95690437,  0.86448982,  1.00807034,  0.76752396,  0.27534839,
         0.05644369],
       [-1.00611074,  0.75805155, -2.1296968 , -1.33495405,  1.90298629,
        -0.23900619],
       [-0.61637267,  1.22298605, -0.98632522,  0.27776388,  1.26263451,
        -0.8791963 ],
       [ 0.37372154,  0.07208375, -0.2599208 ,  0.25160064, -0.97166685,
        -0.88585812]])

In [89]:
arr10 = np.random.randn(10, 7)
arr10

(10, 7)

In [90]:
arr10[arr10>0]

array([0.63314799, 0.42451902, 0.83963994, 0.56579489, 1.11293382,
       1.7433862 , 0.24269097, 1.08124451, 1.13479996, 1.17616956,
       0.19605282, 1.19785951, 1.63054334, 0.52409041, 0.97723849,
       0.11853861, 0.02836536, 1.5247277 , 0.0792557 , 0.09727779,
       0.69370541, 0.67979384, 0.41577922, 2.20008777, 1.02069508,
       0.18366662, 0.96960738, 0.48952841, 1.0631263 , 0.78748273,
       1.91461553, 0.19449899])

In [93]:
#Comando booleando substituindo valores
arr10[arr10<0] = 0
arr10

array([[0.        , 0.63314799, 0.42451902, 0.        , 0.        ,
        0.        , 0.        ],
       [0.83963994, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.56579489],
       [1.11293382, 0.        , 1.7433862 , 0.24269097, 1.08124451,
        0.        , 0.        ],
       [1.13479996, 0.        , 1.17616956, 0.        , 0.        ,
        0.19605282, 1.19785951],
       [0.        , 1.63054334, 0.52409041, 0.97723849, 0.        ,
        0.11853861, 0.        ],
       [0.02836536, 0.        , 0.        , 1.5247277 , 0.0792557 ,
        0.09727779, 0.69370541],
       [0.        , 0.67979384, 0.        , 0.        , 0.        ,
        0.41577922, 0.        ],
       [2.20008777, 1.02069508, 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.18366662, 0.        , 0.        , 0.        , 0.96960738,
        0.48952841, 1.0631263 ],
       [0.78748273, 0.        , 1.91461553, 0.        , 0.        ,
        0.        , 0.1

In [94]:
arr10 >0

array([[False,  True,  True, False, False, False, False],
       [ True, False, False, False, False, False,  True],
       [ True, False,  True,  True,  True, False, False],
       [ True, False,  True, False, False,  True,  True],
       [False,  True,  True,  True, False,  True, False],
       [ True, False, False,  True,  True,  True,  True],
       [False,  True, False, False, False,  True, False],
       [ True,  True, False, False, False, False, False],
       [ True, False, False, False,  True,  True,  True],
       [ True, False,  True, False, False, False,  True]])

In [126]:
arr10 = np.random.randn(7, 7)
arrmask = np.array(['Seg','Ter', 'Qua', 'Qui','Sex', 'Sab', 'Dom'])
arr10

array([[-0.96938111, -1.53880547, -1.21658835, -1.30406808, -0.73041662,
        -0.04908948, -0.53422413],
       [ 1.33583646, -1.68080715,  0.65746144, -1.77722022,  1.71292677,
         0.6397051 ,  1.17191067],
       [-1.07389531,  0.60981162,  1.40784496, -0.64335927,  0.08890418,
        -1.23302367, -1.7776463 ],
       [-1.52053078, -0.06748091, -0.33678327, -0.9485274 ,  0.15710372,
         1.43496216, -0.5089681 ],
       [ 0.6455309 , -0.87574278,  0.50237601,  1.3862864 , -0.20345629,
         0.25212235, -0.98266291],
       [-0.18820975,  1.9027834 , -1.59281699, -0.04524577, -0.8422796 ,
         1.47559094,  0.99085345],
       [-0.28544479,  0.53712512,  1.65077193,  2.50201926,  0.50133819,
        -0.096169  , -1.35682241]])

In [120]:
arr10[arrmask == 'Dom']

array([[-1.31328775,  0.63963106,  0.50895245, -1.30923195,  1.4032003 ]])

In [121]:
#Transpor
arr10.T

array([[-0.05389624,  0.48594182,  0.49017718,  0.80912581, -0.18510238,
        -0.34231337, -1.31328775],
       [-0.94436141, -2.25337444,  1.53612865, -0.11459425, -1.40898167,
        -1.12492426,  0.63963106],
       [ 1.2469635 ,  1.56518029, -0.78901943,  1.01473059, -0.12968884,
        -1.98632525,  0.50895245],
       [ 0.99014162,  1.49247215, -0.8771184 ,  0.59337267,  0.68919398,
         1.14119844, -1.30923195],
       [ 0.59131534, -0.60994297,  0.72028492,  0.46040488, -0.65215388,
        -0.44181312,  1.4032003 ]])

In [127]:
#Jogar a mascara para a linha das colunas
arr10[:,arrmask == 'Seg']

array([[-0.96938111],
       [ 1.33583646],
       [-1.07389531],
       [-1.52053078],
       [ 0.6455309 ],
       [-0.18820975],
       [-0.28544479]])

In [ ]:
arr10[]